-- Criação da tabela de clientes
CREATE TABLE clientes (
    cpf VARCHAR2(11) PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    data_de_nascimento DATE NOT NULL,
    telefone VARCHAR2(15),
    email VARCHAR2(100)
);

-- Criação da tabela de veículos
CREATE TABLE veiculos (
    placa VARCHAR2(7) PRIMARY KEY,
    marca VARCHAR2(50) NOT NULL,
    modelo VARCHAR2(50) NOT NULL,
    ano_fabricacao NUMBER(4) CHECK (ano_fabricacao >= 1886 AND ano_fabricacao <= EXTRACT(YEAR FROM SYSDATE))
);

-- Criação da tabela de diagnósticos
CREATE TABLE diagnosticos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa VARCHAR2(7) NOT NULL,
    problema VARCHAR2(255) NOT NULL,
    descricao VARCHAR2(255),
    data_diagnostico DATE DEFAULT SYSDATE,
    FOREIGN KEY (placa) REFERENCES veiculos(placa)
);